### ISSUE TITLE
Test suite runs too long

### ISSUE THREAD

**Issue by peti** [litherum/punycode#1]
Hi, I've tried to build punycode on my EeePC laptop and found that the test suite runs well in excess of 20 minutes! Is that really necessary?

**Comment by litherum** [comment]
The reason it takes so long is the "{maxSuccess = 1000000, maxSize = 100}" on Main.hs lines 157-160. Without setting the number of trials that high, the tests were reporting successful, even though I had bugs in my code. If you want the tests to run more quickly, you can set those thresholds lower, but be warned that they might not find all your bugs. Most users don't end up running tests when they build packages, so I figured having a long-running test suite would be okay.

**Comment by peti** [comment]
I see. Well, the problem I have is that I'm packing punycode for the [NixOS Linux distribution](http://nixos.org), and we run the test suits every time the package is built to verify that the version we distribute is sort-of stable.  Of course, we're building many, many packages, so we're somewhat sensitive to the time it takes to run those tests.In case of punycode, I just disabled the test suite in the package description to save our build farm some time. It's not ideal, but given our hardware constraints it's probably the best way to deal with the situation.

**Comment by litherum** [comment]
In your build system, is it possible to modify the package source before the tests are run? You could apply a small patch to make the number of trials smaller (similar to how FreeBSD's ports system has a "patch" step). Unfortunately, I don't think I'm comfortable decreasing that limit in the official repo, because of my correctness concerns stated above. :-(

**Comment by peti** [comment]
Well, if you doubt that your test suite catches errors when run with
reduced size parameters, then it's probably not worthwhile for us to run
it with reduced size parameters either.
